// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt9YcP2XgOhff-JEaOalXUeJIlGS-L3eE',
    appId: '1:842226582723:web:4f8280a394dedb09364e76',
    messagingSenderId: '842226582723',
    projectId: 'laundry-aab5c',
    authDomain: 'laundry-aab5c.firebaseapp.com',
    storageBucket: 'laundry-aab5c.firebasestorage.app',
    measurementId: 'G-SN29QK36NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChNhse_JjXsxB97iFy18J4L2mOUy2rbRg',
    appId: '1:842226582723:android:f86c078896171329364e76',
    messagingSenderId: '842226582723',
    projectId: 'laundry-aab5c',
    storageBucket: 'laundry-aab5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGR1CHoOx9BYqhB2-5xNct3GUbtd0ftko',
    appId: '1:842226582723:ios:0a5726a628f223a1364e76',
    messagingSenderId: '842226582723',
    projectId: 'laundry-aab5c',
    storageBucket: 'laundry-aab5c.firebasestorage.app',
    iosBundleId: 'com.example.appLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGR1CHoOx9BYqhB2-5xNct3GUbtd0ftko',
    appId: '1:842226582723:ios:0a5726a628f223a1364e76',
    messagingSenderId: '842226582723',
    projectId: 'laundry-aab5c',
    storageBucket: 'laundry-aab5c.firebasestorage.app',
    iosBundleId: 'com.example.appLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt9YcP2XgOhff-JEaOalXUeJIlGS-L3eE',
    appId: '1:842226582723:web:b9be6bcdd6cb245e364e76',
    messagingSenderId: '842226582723',
    projectId: 'laundry-aab5c',
    authDomain: 'laundry-aab5c.firebaseapp.com',
    storageBucket: 'laundry-aab5c.firebasestorage.app',
    measurementId: 'G-BF9LR7SRE9',
  );
}
